apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- role.yaml
- rolebinding.yaml

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: example
    spec:
      template:
        spec:
          serviceAccountName: httpd
          containers:
            - name: httpd
              securityContext:
                runAsUser: 0
                runAsGroup: 0
