apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: httpd-allow-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-anyuid
subjects:
- kind: ServiceAccount
  name: httpd
